Refactor cards controllers
consul/consul pull request #4310
Opened 2021-01-11 12:13 UTC by javierm

## Objectives

* Make it easier to add cards in other sections

2021-01-11 17:17 UTC, Senen requested changes
Hi @javierm, nice refactoring and cleaning work 🧹 👏🏼 .

I found probably a missing spec, and also discovered a translation resolution error introduced because of the new model validation. I added a few commits to share a possible solution and some improvements to make the form look like other admin ones. Let me know what do you think.

The root of the error is the following line of the `admin/widget/cards/_form.html.erb` file:

```
<%= f.submit(t("admin.homepage.#{action_name}.#{@card.header? ? "submit_header" : "submit_card"}"), class: "button success") %>
```

Now when we submit a card without title the `action_name` part of the expression is resolved to [:create | :update] and we do not have translations for that entries so I decided to extract the form to a component so we can handle that kind of logic in the way we are doing these days.

2021-01-12 13:50 UTC, javierm commented on app/models/abilities/administrator.rb
> +      can :manage, Widget::Card
Done! :+1:

2021-01-12 13:50 UTC, javierm commented on app/views/admin/site_customization/cards/index.html.erb
> +        new_admin_site_customization_page_widget_card_path(@page), class: "button" %>
I don't know :sweat_smile:. We don't have clear criteria regarding multiline statements :thinking:. I've changed it so it looks as you suggested anyway.

2021-01-12 13:53 UTC, javierm commented
> The root of the error is the following line of the `admin/widget/cards/_form.html.erb` file:
> 
> ```
> <%= f.submit(t("admin.homepage.#{action_name}.#{@card.header? ? "submit_header" : "submit_card"}"), class: "button success") %>
> ```

I've used the `admin_submit_action` helper as we do in other places. Does it look OK for you? I was going to use ActiveRecord model translations, but since we use a different text for header cards, it's a bit hard :thinking:.

2021-01-12 15:01 UTC, Senen approved these changes

2021-01-14 16:34 UTC, merged