Add SDG target tags and filter
consul/consul pull request #4324
Opened 2021-01-21 17:29 UTC by javierm

## References

* Goal tags and filters were added in pull requests #4305 and #4300

## Objectives

* Make it possible to filter debates, proposals and budget investments by SDG target
* Display associated SDG targets alongside associated SDGs

## Visual Changes

TODO

2021-01-22 13:39 UTC, Senen requested changes
Hi Javi, here are the issues I found:

1º There are some missing translations. See attached patch: `TagListComponenetLocalTargetTitles.txt`

2º I think I found a case when the see more link of SDG::Goal::TagListComponent is not working properly. To reproduce the issue you can assign more targets or local targets to a relatable but do not save the direct relation with their goals, this happens because the method `count_out_of_limit` only considers the relatable goals number. If we are always going to ensure to save the direct relation with the goal we probably can let it as it is.
Check the attached patch called: `TagListComponenetSeeMoreLimit.txt`

And the last visual thing is the text color of the "See more" link. Check the image below:
<img width="793" alt="Captura de pantalla 2021-01-22 a las 14 31 01" src="https://user-images.githubusercontent.com/15726/105496954-7916a180-5cbe-11eb-871c-64050088d89d.png">

**Patches**
[TagListComponentLocalTargetsTitles.txt](https://github.com/consul/consul/files/5856145/TagListComponentLocalTargetsTitles.txt)
[TagListComponentSeeMoreLimit.txt](https://github.com/consul/consul/files/5856151/TagListComponentSeeMoreLimit.txt)


I left two more comments at code.

2021-01-22 14:46 UTC, javierm commented
Thanks for the review! I've added the changes you mentioned. We might need to review the "limit" thing in the future, but I guess using the same interface and limit we use for tags is OK for now :thinking:.

2021-01-26 19:19 UTC, Senen approved these changes
👍🏼

2021-01-27 15:47 UTC, Senen approved these changes

2021-01-27 15:48 UTC, merged