Budgets info section
consul/consul pull request #4508
Opened 2021-05-10 15:20 UTC by taitus

## References
- This is part of pull request #4198

## Objectives
Add supports info section on budgets index page.

## Visual Changes
![Captura de pantalla 2021-05-10 a las 17 18 50](https://user-images.githubusercontent.com/16189/117683111-07eaf380-b1b4-11eb-9f9c-84c0e6f02ae3.png)

## Notes
Merge after #4507

2021-05-27 17:57 UTC, Senen requested changes
Hi @taitus, I found some minor things. Let me know what you think. ☺️

2021-05-27 19:26 UTC, javierm commented on app/components/budgets/supports_info_component.html.erb
> +      <%= image_tag("budgets/budgets_support.png", alt: "", class: "margin") %>
@Senen IMHO this is a [decorative image](https://www.w3.org/WAI/tutorials/images/decorative/) :thinking:, so leaving the alt attribute blank is fine.

We could also remove this line and add the image using CSS pseudoelements like `.supports-info .callout h2::after` :thinking:. That way other CONSUL installations could customize the image without changing ERB files.

2021-05-28 11:53 UTC, Senen commented on app/components/budgets/supports_info_component.html.erb
> +      <%= image_tag("budgets/budgets_support.png", alt: "", class: "margin") %>
It's ok with me. I was worried about what accessibility validators would say, but I guess you already know that there will be no problem. 👍🏼

2021-06-07 13:41 UTC, Senen commented on app/components/budgets/investments_list_component.html.erb
> +  <section id="investments-list" class="investments-list">
I was wrong, the id is needed [here](https://github.com/consul/consul/pull/4508/files#diff-a32c142943c511497cdad9a4143e0439b2932645407e93647d2b004999abad42R29).

2021-06-14 12:09 UTC, javierm approved these changes

2021-06-14 12:10 UTC, merged