Add hide money option for approval budgets
consul/consul pull request #4601
Opened 2021-07-28 15:02 UTC by decabeza

## Objectives

Sometimes administrators want to create a participatory budgeting process with their phases and features. But for different reasons don't want money involved.

For example, sometimes citizens can propose projects that a City Council can do at no cost, and they don't want to show 0€ in all investment projects. Or maybe the City Council creates the projects, and the citizens only vote for them.

This PR adds the option to hide money on budgets with type approval hiding any money amount for that participatory budget.

## Visual Changes

<img width="772" alt="hide_money" src="https://user-images.githubusercontent.com/631897/127345883-b607c1ab-382e-4384-96f1-b20953168f76.png">

2022-02-28 10:17 UTC, taitus commented
@senen I have split the PR into different commits to facilitate the review. Once reviewed, we can unify it again in one commit, if we consider it appropriate.

2022-03-29 11:09 UTC, Senen requested changes
Hi @taitus, I found super minor things, let me know what you think.

>@Senen I have split the PR into different commits to facilitate the review. Once reviewed, we can unify it again in one commit, if we consider it appropriate.

As you guessed, split commits helped me a lot during review. I think we can do the merge this way.

2022-03-29 17:32 UTC, taitus approved these changes

2022-03-30 07:54 UTC, Senen approved these changes
👍🏼

2022-03-30 07:58 UTC, merged